service: test-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

functions:
  createUser:
    handler: handlers/user.createUser
    events:
      - http:
          path: user
          method: post
          cors: true
  getAllUser:
    handler: handlers/user.getAllUser
    events:
      - http:
          path: users
          method: get
          cors: true
  getOneUser:
    handler: handlers/user.getOneUser
    events:
      - http:
          path: user/{id}
          method: get
          cors: true
  updateUser:
    handler: handlers/user.updateUser
    events:
      - http:
          path: user/{id}
          method: patch
          cors: true
  deleteUser:
    handler: handlers/user.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

          